on: release
name: 🚀 Deploy website when pushed
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 16
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        yarn install
        yarn build
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.jbtechlab.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
